### PR TITLE
Feature arc42 11technicalrisks

### LINKED ISSUE #23: Do the "Risk and technical debts" part of the documentation

### PR DESCRIPTION
**Pull request by sarav22**
Closes #23

### CODE REVIEW

**Comment by UO258425** [comment]
LGTM,  Another column could be added with the priority but is nice as it is

**Comment by sarav22** [comment]
> LGTM, Another column could be added with the priority but is nice as it is

What do you mean by another column with the priority, with numbers or how? They are already ordered from higher to lower.

**Comment by UO258425** [comment]
Something like the last column [here](https://www.nchannel.com/wp-content/uploads/2018/12/Retail-Integration-Risk-Chart.png). Just as a visual help. Anyway seems valid as it is now.

**Comment by Raulpemol** [comment]
I don't see the need to have a priority column as they are already ordered by risk. As we are going to use an agile methodology and we will order the kanban by priority, I believe it is consistent to write the risks this way.

**Comment by UO258425** [comment]
Okay, in that case seems fine

**Pull request merged**
