### PR TITLE
Finished proposal for Solution Strategy

### PR DESCRIPTION
**Pull request by luispc1998**
Take a look to the decisions. I believe that here it is stated everything that we have commented these days.

### CODE REVIEW

**Comment by AGM157** [comment]
Are we going to use this as an starting point or are we going to build it from 0?
https://github.com/inrupt/generator-solid-react

**Comment by UO258425** [comment]
> 
> 
> Are we going to use this as an starting point or are we going to build it from 0?
> https://github.com/inrupt/generator-solid-react

I used that some days ago and it's very very useful

**Comment by luispc1998** [comment]
Let's open an slack poll in order to decide it. In any case, we will probably take code from there.

**Comment by UO258425** [comment]
Besides the inrupt generator, LGTM

**Comment by Angelixus** [comment]
I already voted in the poll.

**Comment by luispc1998** [comment]
The inrupt generator is added to the documentation page.

**Comment by AGM157** [comment]
LGTM

**Pull request merged**
